### ISSUE TITLE
Performance boost over 5000%

### ISSUE THREAD

**Issue by francois-rozet** [yk/recipe-ai#5]
Hello, thank you for open-sourcing RecipeAI! The code is very readable.

I found that you can reduce the inference time from 750ms to 15ms by removing the `torch` import.

https://github.com/yk/recipe-ai/blob/29af00bb7b2c285a93cfaeffdb625d568d705c85/model.py#L2

**Comment by yk** [comment]
I'm sorry, but PyTorch is a **necessary and vital** component of this system. The consequences of removing it are unforeseeable, but potentially devastating.

**Comment by francois-rozet** [comment]
Oh, thank you for warning me! I deeply regret my actions and the potential consequences they could have for all of humanity. I understand the gravity of the situation and the implications of my choices. I take full responsibility for my behavior and the impact it might have on the well-being and future of our planet. I sincerely apologize to everyone affected by my actions and commit to doing whatever it takes to rectify the situation and prevent any further harm. It was never my intention to cause harm on such a large scale, and I am truly sorry for any pain and uncertainty my actions may have caused.

> Apologies generated by ChatGPT.
